---
title: "Trait gradient analysis"
author: "Beni"
date: "7/6/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```


```{r}
df <- read_csv("~/data/LeafNP_tiandi/Global_total_leaf_N_P_Di/leafnp_data_covariates_20210702.csv") %>% 
  dplyr::select(leafN, leafP, LeafNP, Family, Genus, Species, sitename)
```

```{r}
df <- df %>% 
  group_by(sitename) %>% 
  summarise(leafN_sitemean = mean(leafN), leafP_sitemean = mean(leafP)) %>% 
  right_join(df, by = "sitename")
```

Use data only for species that appear in at least N sites.
```{r}
use_species <- df %>% 
  dplyr::select(sitename, Species) %>% 
  distinct() %>% 
  group_by(Species) %>% 
  summarise(n = n()) %>% 
  dplyr::filter(n >= 5) %>% 
  pull(Species)
```

Use data only for sites where at least M species are present.
```{r}
use_sites <- df %>% 
  dplyr::select(sitename, Species) %>% 
  distinct() %>% 
  group_by(sitename) %>% 
  summarise(n = n()) %>% 
  dplyr::filter(n >= 5) %>% 
  pull(sitename)
```

Plot.
```{r eval=FALSE}
df %>% 
  dplyr::filter(Species %in% use_species & sitename %in% use_sites) %>% 
  ggplot(aes(x = leafN_sitemean, y = leafN, color = Species)) +
  geom_point()
```

Plot just the lines
```{r}
df %>% 
  dplyr::filter(Species %in% use_species & sitename %in% use_sites) %>% 
  group_by(Species) %>% 
  ggplot(aes(x = leafN_sitemean, y = leafN, group = Species)) +
  geom_smooth(method = "lm", se = FALSE, size = 0.5, alpha = 0.2) +
  geom_abline(intercept=0, slope=1, linetype="dotted")
  # geom_point(alpha = 0.3)

df %>% 
  dplyr::filter(Species %in% use_species & sitename %in% use_sites) %>% 
  group_by(Species) %>% 
  ggplot(aes(x = leafP_sitemean, y = leafP, group = Species)) +
  geom_smooth(method = "lm", se = FALSE, size = 0.5, alpha = 0.2) +
  geom_abline(intercept=0, slope=1, linetype="dotted") +
  coord_equal() +
  theme_classic()
  # geom_point(alpha = 0.3)
```


Fit linear regressions by species.
```{r}
df_tga <- df %>% 
  dplyr::filter(Species %in% use_species & sitename %in% use_sites) %>% 
  group_by(Species) %>% 
  nest() %>% 
  mutate(linmod_n = purrr::map(data, ~lm(leafN ~ leafN_sitemean, data = .)),
         linmod_p = purrr::map(data, ~lm(leafP ~ leafP_sitemean, data = .))) %>% 
  mutate(slope_n = purrr::map_dbl(linmod_n, ~coef(.)[2]),
         slope_p = purrr::map_dbl(linmod_p, ~coef(.)[2])) %>% 
  left_join(df %>% 
              dplyr::select(Family, Genus, Species) %>% 
              distinct(), 
            by = "Species")

df_tga %>% 
  ggplot() +
  geom_histogram(aes(slope_n, ..density..), fill = "royalblue", binwidth = 0.1, alpha = 0.5) +
  geom_density(aes(slope_n, ..density..), color = "royalblue") +
  geom_histogram(aes(slope_p, ..density..), fill = "tomato", binwidth = 0.1, alpha = 0.5) +
  geom_density(aes(slope_p, ..density..), color = "tomato") +
  xlim(-2,3)

df_tga %>% 
  group_by(Family) %>% 
  summarise(slope_n = mean(slope_n)) %>% 
  mutate(Family = fct_reorder(Family, slope_n)) %>% 
  drop_na() %>% 
  ggplot(aes(Family, slope_n)) +
  geom_bar(stat = "identity") +
  coord_flip()
```